extends RefCounted


const LOCK_SYMBOLS: String = "LOCK_SYMBOLS"
const OBFUSCATE_STRINGS: String = "OBFUSCATE_STRINGS"
const OBFUSCATE_STRING_PARAMETERS: String = "OBFUSCATE_STRING_PARAMETERS"
const FEATURE_FUNC: String = "FEATURE_FUNC"
